(defun prind (x)
  (cond
    ((consp x)
     (princ "(")
     (prind (car x))
     (princ " . ")
     (prind (cdr x))
     (princ ")"))
    (t (princ x))))

(princ "> ")
(prind 'xxx)
(print '>)
(prind (cons 'a 'b))
(print '>)
(prind '(a (b) c))
(print '>)
(prind '((a b) (b) c))
(print '-)